.database:deploy:template:
  stage: deploy
  when: manual
  script:
    - docker-compose up -d database;
    - docker-compose exec -T database bash /docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh;

database:deploy:develop:
  extends:
    - .develop:stage:template
    - .database:deploy:template

database:deploy:stage:
  extends:
    - .stage:stage:template
    - .database:deploy:template

database:deploy:production:
  extends:
    - .production:stage:template
    - .database:deploy:template
