.rabbitmq:deploy:template:
  stage: deploy
  when: manual
  script:
    - docker-compose up -d rabbitmq;

rabbitmq:deploy:develop:
  extends:
    - .develop:stage:template
    - .rabbitmq:deploy:template

rabbitmq:deploy:stage:
  extends:
    - .stage:stage:template
    - .rabbitmq:deploy:template

rabbitmq:deploy:production:
  extends:
    - .production:stage:template
    - .rabbitmq:deploy:template
